name: Terraform Apply

on:
  push:
    branches:
      - dev
      - prod

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::414669981241:role/terraform-deploy-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Apply
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [ "$BRANCH_NAME" = "prod" ]; then
            terraform apply -auto-approve -var-file=envs/prod/main.tfvars
          else
            terraform apply -auto-approve -var-file=envs/dev/main.tfvars
          fi
