name: Terraform Plan

on:
  pull_request:
    branches:
      - dev
      - prod

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      DEV_ACCOUNT_ID: "414669981241"
      PROD_ACCOUNT_ID: "151632973153"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Choose env (dev/prod) from base branch
        id: env
        shell: bash
        run: |
          if [ "${{ github.base_ref }}" = "prod" ]; then
            echo "ENV=prod" >> "$GITHUB_ENV"
            echo "AWS_ACCOUNT_ID=${{ env.PROD_ACCOUNT_ID }}" >> "$GITHUB_ENV"
          else
            echo "ENV=dev" >> "$GITHUB_ENV"
            echo "AWS_ACCOUNT_ID=${{ env.DEV_ACCOUNT_ID }}" >> "$GITHUB_ENV"
          fi

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/terraform-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Terraform Init (via Make)
        run: |
          if [ "${{ env.ENV }}" = "prod" ]; then
            make init-prod
          else
            make init-dev
          fi

      - name: Terraform Validate (via Make)
        run: make validate

      - name: Terraform Plan (via Make)
        run: |
          if [ "${{ env.ENV }}" = "prod" ]; then
            make plan-prod
          else
            make plan-dev
          fi
